language: objective-c
#osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="Mechanica iOS"
  - MACOS_FRAMEWORK_SCHEME="Mechanica macOS"
  - TVOS_FRAMEWORK_SCHEME="Mechanica tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="Mechanica watchOS"
  #- WORKSPACE=Mechanica.xcworkspace
  #- EXAMPLE_SCHEME="Mechanica Example"
  
matrix:
  include:
    - osx_image: xcode9
      #xcode_sdk: iphonesimulator11.0
      #TOOD: enable pod lint for iOS destination in the future
      env: DESTINATION="OS=11.0,name=iPhone 7 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="iphonesimulator11.0"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="ios"
    - osx_image: xcode9
      #xcode_sdk: watchsimulator4.0
      env: DESTINATION="OS=4.0,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  SDK="watchsimulator4.0"     RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="watchos"
    - osx_image: xcode9
      #xcode_sdk: appletvsimulator11.0
      env: DESTINATION="OS=11.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     SDK="appletvsimulator11.0"  RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="tvos"
    - osx_image: xcode9
      #xcode_sdk: macosx10.13
      env: DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"    SDK="macosx10.13"           RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="macos"
    - osx_image: xcode9
      #xcode_sdk: iphonesimulator11.0
      env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="iphonesimulator11.0"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"  CODECOV_FLAG="ios10"
    # - osx_image: xcode8.3
    #   #xcode_sdk: iphonesimulator10.3
    #   env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus"    SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="iphonesimulator10.3"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"   CODECOV_FLAG="ios"
    # - osx_image: xcode8.3
    #   #xcode_sdk: iphonesimulator10.3
    #   env: DESTINATION="S=10.3.1,name=iPhone 5"          SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="iphonesimulator10.3"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"   CODECOV_FLAG="ios-32bit"
    # - osx_image: xcode8.3
    #   #xcode_sdk: watchsimulator3.2
    #   env: DESTINATION="OS=3.2,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  SDK="watchsimulator3.2"     RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="watchos"
    # - osx_image: xcode8.3
    #   #xcode_sdk: appletvsimulator10.2
    #   env: DESTINATION="OS=10.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     SDK="appletvsimulator10.2"  RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="tvos"
    # - osx_image: xcode8.3
    #   #xcode_sdk: macosx10.12
    #   env: DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"    SDK="macosx10.12"           RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="macos"

  #matrix:
    # - DESTINATION="OS=3.2,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="watchos"
    # - DESTINATION="OS=10.3.1,name=iPhone 5"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"   CODECOV_FLAG="ios-32bit"
    # - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"    SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"   CODECOV_FLAG="ios"
    # - DESTINATION="OS=10.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="tvos"
    # - DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="macos"

    #TOOD: enable pod lint for iOS destination in the future
    # - DESTINATION="OS=11.0,name=iPhone 7 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="iphonesimulator11.0"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="ios"
    # - DESTINATION="OS=4.0,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  SDK="watchsimulator4.0"     RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="watchos"
    # - DESTINATION="OS=11.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     SDK="appletvsimulator11.0"  RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="tvos"
    # - DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"    SDK="macosx10.13"           RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"    CODECOV_FLAG="macos"

# skip release group defined in Gemfile
bundler_args: --without release

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - brew install swiftlint
  # fix for watchOS until https://github.com/travis-ci/travis-ci/issues/7580 is fixed
  - xcrun simctl delete 38C891AB-EC79-43E4-9311-6FDEB12DCF11 || true

before_script:
  - swiftlint --reporter "emoji"

script:
  - set -o pipefail
  # The xcrun with devices here will print out a list of available devices you can snag the UDIDs for
  - xcrun instruments -s devices
  - xcodebuild -version
  - xcodebuild -showsdks
  - swift --version

  # Build Framework in DEBUG and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES build-for-testing test-without-building | xcpretty;
      bash <(curl -s https://codecov.io/bash) -J 'Mechanica' -cF "$CODECOV_FLAG"
    else
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in RELEASE and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build-for-testing test-without-building | xcpretty;
    else
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
  - sleep 5